apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-node-exporter
    jobLabel: node-exporter
    release: prometheus
  name: prometheus-prometheus-node-exporter
  namespace: monitoring
spec:
  endpoints:
  - port: http-metrics
    scheme: http
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        targetLabel: nodename
        replacement: $1
        action: replace
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - kube-state
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: kubestate